[package]
name = "rml"
version = "0.1.0"
authors = ["Moritz Drexl <Moritz.Drexl@target.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = { version = "0.13.1", features = ["blas"] }
cblas = "0.2.0"
blas-src = { version = "0.6.1", features = ["accelerate"] }
